### PR TITLE
fix some HTML quirks

### PR DESCRIPTION
**Pull request by dmitmel**
Just a couple of small fixes. Also, your files have mixed indentation, do you prefer tabs or spaces? I need to know that so that I can re-format your files with a tool called [Prettier](https://prettier.io/).

### CODE REVIEW

**Comment by koalaman** [comment]
Thanks! I definitely prefer spaces.

**Comment by dmitmel** [comment]
Okay, I'll open a new PR with fixed formatting then. Can you merge this one, #14 and #15? I can rebase them if you want so that you don't have to resolve merge conflicts.

**Comment by koalaman** [comment]
Sure. Would you mind just having them as multiple commits in a single PR? That way I'll know the order and such.

**Comment by dmitmel** [comment]
[Here ya go](#16)

**Pull request merged**
